name: Check and Push Version Tag

on:
  push:
    branches:
      - main  # 只在主分支上触发
    paths:
      - 'version'  # 只有version文件变化时触发

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat version)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "${{ steps.get_version.outputs.VERSION }}" | wc -l)
          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_OUTPUT

      - name: Set up Go
        if: steps.check_tag.outputs.TAG_EXISTS == '0'
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5' # Specify a Go version

      - name: Get dependencies
        if: steps.check_tag.outputs.TAG_EXISTS == '0'
        run: go get -v -t -d ./...

      - name: Get test
        if: steps.check_tag.outputs.TAG_EXISTS == '0'
        run: go test -timeout 10s ./...

      - name: Push tag if not exists
        if: steps.check_tag.outputs.TAG_EXISTS == '0'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "${{ steps.get_version.outputs.VERSION }}"
          git push origin "${{ steps.get_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}